FROM node:16.14.2-stretch-slim as build-staging

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env.staging .env
RUN npm run build:staging

FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx-staging.conf /etc/nginx/conf.d/nginx.conf
COPY --from=build-staging /app/dist /usr/share/nginx/html
EXPOSE 8000